// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.RecycleRush.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class PickupGrayTotes extends CommandGroup {
    
    public  PickupGrayTotes() {
    	addSequential(new DriveForwardRangeFinder());
    	addParallel(new ArmCommand(false));
    	addSequential(new ArmCommand(true));
    	addSequential(new ElevatorCommand(true, false));
    	addSequential(new ElevatorCommand(true, true));
    	//TODO: Find out right value below
    	addParallel(new DriveAuto(false, 2));
    	addSequential(new TurnCommand(false));
    	//TODO: Find out right value
    	addSequential(new DriveAuto(true, 4));
        addSequential(new ElevatorCommand(false, false));
        addSequential(new ElevatorCommand(false, true));
        addSequential(new ArmCommand(false));
        //TODO: Find the value below...again
        addSequential(new DriveAuto(false, 5));
    	addSequential(new TurnCommand(true));
    	//TODO: Find out the other value
        addSequential(new DriveAuto(true, 2));
        addSequential(new ArmCommand(true));
        addSequential(new ElevatorCommand(true, false));
        addSequential(new ElevatorCommand(true, true));
        //TODO: Find yet another value. Also if this should be parallel
        addParallel(new DriveAuto(false, 2));
        addSequential(new TurnCommand(false));
        //TODO: Find the value...
        addSequential(new DriveAuto(true, 5));
        addSequential(new ElevatorCommand(false, false));
        addSequential(new ElevatorCommand(false, true));
        addSequential(new ArmCommand(false));
        //TODO: Find another value
        addSequential(new DriveAuto(false, 4));
        addSequential(new TurnCommand(true)); //TODO: check value
        //TODO: Replace value with amount to get to Auto Zone. Maybe DriveForwardRangeFinder
        addSequential(new DriveAuto(false, 4));
    }
}
