// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5506.RecycleRush.subsystems;

import org.usfirst.frc5506.RecycleRush.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Elevator extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid leftSolenoid = RobotMap.elevatorleftSolenoid;
    DoubleSolenoid rightSolenoid = RobotMap.elevatorrightSolenoid;
    DigitalInput limitSwitch = RobotMap.elevatorlimitSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void elevatorUp() {
    	leftSolenoid.set(DoubleSolenoid.Value.kForward);
    	rightSolenoid.set(DoubleSolenoid.Value.kForward);
    }
    
    public void elevatorDown() {
    	leftSolenoid.set(DoubleSolenoid.Value.kReverse);
    	rightSolenoid.set(DoubleSolenoid.Value.kReverse);
    }

	public void stop() {
		leftSolenoid.set(DoubleSolenoid.Value.kOff);
		rightSolenoid.set(DoubleSolenoid.Value.kOff);
	}
	
	public DigitalInput getLimitSwitch() {
		return limitSwitch;
	}
}


